# language: php
filter:
    excluded_paths:
        - 'tests/*'
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false
        braces:
            classes_functions:
                class: end-of-line
                function: end-of-line
                closure: end-of-line
            if:
                else_on_new_line: true
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
                while_on_new_line: true
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
                catch_on_new_line: true
                finally_on_new_line: true
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower
checks:
    php:
        uppercase_constants: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unreachable_code: true
        single_namespace_per_use: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_php_tag_first: true
        properties_in_camelcaps: true
        php5_style_constructor: true
        parameters_in_camelcaps: true
        optional_parameters_at_the_end: true
        one_class_per_file: true
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        no_trailing_whitespace: true
        no_short_variable_names:
            minimum: '3'
        no_short_open_tag: true
        no_short_method_names:
            minimum: '3'
        no_goto: true
        no_global_keyword: true
        no_exit: true
        no_eval: true
        no_commented_out_code: true
        newline_at_end_of_file: true
        instanceof_class_exists: true
        function_in_camel_caps: true
        duplication: true
        classes_in_camel_caps: true
        catch_class_exists: true
        blank_line_after_namespace_declaration: true
        avoid_usage_of_logical_operators: true
        avoid_duplicate_types: false
        avoid_closing_tag: true
        avoid_aliased_php_functions: true
        symfony_request_injection: false
        verify_argument_usable_as_reference: false
        too_many_arguments: false
        precedence_mistakes: false
        precedence_in_conditions: false
        no_duplicate_arguments: true
        foreach_usable_as_reference: false
        avoid_entity_manager_injection: false
        switch_fallthrough_commented: false
        psr2_switch_declaration: false
        psr2_class_declaration: false
        avoid_superglobals: false
build:
    tests:
        override:
            -
                command: 'phpunit -c phpunit.xml --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'php-clover'
