language: php
php:
  - 5.4
  - 5.5
before_script:
  - echo "extension=memcache.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
script: phpunit -c ./tests/phpunit.xml --coverage-text
