
language: php
php:
  - 5.5
  - 5.6
  - hhvm
before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
script:
  - phpunit -c phpunit.xml;
