language: php
php:
  - 5.4
  - 5.5
  - hhvm
matrix:
  allow_failures:
      - php: hhvm
  fast_finish: true
before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
script:
  - phpunit -c ./tests/phpunit.xml --coverage-text
